version: '3'
services:
    databaseserver:
        image: database-img
        container_name: databaseserver
        build:
            context: ../OASIP-Database
        ports:
            - 3306:3306

    backendserver:
        image: backend-img
        container_name: backendserver
        build:
            context: ../OASIP-BackEnd
        depends_on:
            - databaseserver
        links:
            - databaseserver:databseserver
        ports:
            - 3000:3000

    frontendserver:
        image: frontend-img
        container_name: frontendserver
        build:
            context: ../OASIP-FrontEnd
        depends_on:
            - databaseserver
            - backendserver
        ports:
            - 8080:80

    reverse-proxy:
        image: nginx:1.23
        container_name: reverseproxyserver
        depends_on:
            - databaseserver
            - backendserver
            - frontendserver
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ../cert/oasip-ssi4.crt:/etc/ssl/certs/oasip-ssi4.crt
            - ../certs/privatekey.key:/etc/ssl/private/oasip-ssi4.key
        ports:
            - 443:443
            - 80:80
