version: '3'

services:
    databaseserver:
        image: database-img
        container_name: databaseserver
        build:
            context: ./database/
        ports:
            - 3306:3306
        restart: on-failure

    backendserver:
        image: backend-img
        container_name: backendserver
        build:
            context: ./Back-End/OASIP-BACKEND
        depends_on:
            - databaseserver
        links:
            - databaseserver:mysql
        ports:
            - 3000:3000
        restart: on-failure

    frontendserver:
        image: frontend-img
        container_name: frontendserver
        build:
            context: ./Front-End
        depends_on:
            - databaseserver
            - backendserver
        ports:
            - 8080:80
        restart: on-failure

    reverse-proxy:
        image: nginx:1.17.10
        container_name: reverseproxyserver
        depends_on:
            - databaseserver
            - backendserver
            - frontendserver
        volumes:
            - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
